backend:
  name: github
  repo: x1aohe1/x1aohe1.github.io  # 你的仓库
  branch: main              # 默认分支
  base_url: https://x1aohe1.github.io  # 你的站点地址（可选）

media_folder: "static/images"  # 媒体文件存储路径
public_folder: "/images"       # 网站中访问图片的路径

collections:
  # 故事日志集合
  - name: "stories"
    label: "故事日志"
    folder: "content/stories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布时间", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "string" }
      - { label: "正文", name: "body", widget: "markdown" }

  # 项目集合
  - name: "projects"
    label: "项目"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "项目名称", name: "title", widget: "string" }
      - { label: "创建时间", name: "date", widget: "datetime" }
      - { label: "进度", name: "progress", widget: "number", value_type: "int" }
      - { label: "需求", name: "needs", widget: "list", default: [] }
      - { label: "项目描述", name: "description", widget: "string" }
      - { label: "详细内容", name: "body", widget: "markdown" }