backend:
  name: github
  repo: x1aohe1/x1aohe1.github.io
  branch: main
  base_url: https://x1aohe1.github.io
  auth_type: web  # 改为 web
  client_id: Ov23liUDGabIOat1t2KY
  scope: repo,user:email  # 添加这行git-gateway
  
  site_url: https://x1aohe1.github.io/x1aohe1.github.io
  display_url: https://x1aohe1.github.io/x1aohe1.github.io

publish_mode: editorial_workflow # 可选，但推荐使用，可以提供草稿功能
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }